type CommunitySoundTuple = readonly [
  id: string,
  title: string,
  cylinders: number,
  duration: string,
  file: string,
];

const edvvc: CommunitySoundTuple[] = [
  [
    "alfa-romeo-8c-spider",
    "Alfa Romeo 8C Spider",
    8,
    "0:07",
    "Alfa Romeo 8C Spider.ogg",
  ],
  ["ariel-atom-3", "Ariel Atom 3", 4, "0:09", "Ariel Atom 3.ogg"],
  [
    "aston-martin-rapide",
    "Aston Martin Rapide",
    12,
    "0:10",
    "Aston Martin Rapide.ogg",
  ],
  [
    "aston-martin-v12-vantage",
    "Aston Martin V12 Vantage",
    12,
    "0:09",
    "Aston-Martin-V12-Vantage.ogg",
  ],
  [
    "bugatti-veyron-grand-sport",
    "Bugatti Veyron Grand Sport",
    16,
    "0:09",
    "Bugatti Veyron Grand Sport.ogg",
  ],
  [
    "chevrolet-corvette-c6-zr1-recorded2010",
    "Chevrolet Corvette C6 ZR1",
    8,
    "0:12",
    "Chevrolet Corvette C6 ZR1 recorded2010.ogg",
  ],
  [
    "ferrari-458-italia",
    "Ferrari 458 Italia",
    8,
    "0:12",
    "Ferrari 458 Italia.ogg",
  ],
  ["ferrari-599-gto", "Ferrari 599 GTO", 12, "0:09", "Ferrari 599 GTO.ogg"],
  [
    "ferrari-california-2009",
    "Ferrari California",
    8,
    "0:07",
    "Ferrari California (2009).ogg",
  ],
  [
    "ferrari-scuderia-spider-16m",
    "Ferrari Scuderia Spider 16M",
    8,
    "0:09",
    "Ferrari Scuderia Spider 16M.ogg",
  ],
  ["ford-focus-rs", "Ford Focus RS", 5, "0:11", "Ford Focus RS.ogg"],
  ["jaguar-xkr-2009", "Jaguar XKR", 8, "0:09", "Jaguar XKR (2009).ogg"],
  ["koenigsegg-agera", "Koenigsegg Agera", 8, "0:10", "Koenigsegg Agera.ogg"],
  ["koenigsegg-ccx-r", "Koenigsegg CCX-R", 8, "0:10", "Koenigsegg CCX-R.ogg"],
  ["ktm-x-bow", "KTM X-Bow", 4, "0:10", "KTM X-Bow.ogg"],
  [
    "lamborghini-aventador-lp700-4-2011",
    "Lamborghini Aventador LP700-4",
    12,
    "0:08",
    "Lamborghini Aventador LP700-4 (2011).ogg",
  ],
  [
    "lamborghini-gallardo-lp570-4-superleggera",
    "Lamborghini Gallardo Superleggera",
    10,
    "0:10",
    "Lamborghini Gallardo LP570-4 Superleggera.ogg",
  ],
  ["lotus-evora", "Lotus Evora", 6, "0:09", "Lotus Evora.ogg"],
  ["mclaren-mp4-12c", "McLaren MP4-12C", 8, "0:12", "McLaren MP4-12C.ogg"],
  [
    "mercedes-benz-slr-mclaren-722",
    "Mercedes-Benz SLR McLaren 722",
    8,
    "0:09",
    "Mercedes-Benz SLR McLaren 722.ogg",
  ],
  [
    "mercedes-benz-sls-amg",
    "Mercedes-Benz SLS AMG",
    8,
    "0:09",
    "Mercedes-Benz SLS AMG.ogg",
  ],
  ["morgan-3-wheeler", "Morgan 3 Wheeler", 2, "0:20", "Morgan 3 Wheeler.ogg"],
  [
    "morgan-aero-supersports",
    "Morgan Aero Supersports",
    8,
    "0:10",
    "Morgan Aero Supersports.ogg",
  ],
  [
    "nissan-gt-r-specv",
    "Nissan GT-R SpecV",
    6,
    "0:08",
    "Nissan GT-R SpecV.ogg",
  ],
  [
    "pagani-zonda-roadster-f",
    "Pagani Zonda Roadster F",
    12,
    "0:13",
    "Pagani Zonda Roadster F.ogg",
  ],
  ["ruf-ctr3", "RUF CTR3", 6, "0:07", "RUF CTR3.ogg"],
  [
    "spyker-c8-aileron",
    "Spyker C8 Aileron",
    8,
    "0:11",
    "Spyker C8 Aileron.ogg",
  ],
  [
    "vauxhall-vxr8-bathurst-s",
    "Vauxhall VXR8 Bathurst S",
    8,
    "0:09",
    "Vauxhall VXR8 Bathurst S.ogg",
  ],
  [
    "volvo-c30-polestar-concept",
    "Volvo C30 Polestar Concept",
    5,
    "0:12",
    "Volvo C30 Polestar Concept.ogg",
  ],
  [
    "porsche-911r-1967",
    "Porsche 911R (1967)",
    6,
    "0:22",
    "Porsche 911R (1967).ogg",
  ],
  [
    "porsche-997-gt3-rs",
    "Porsche 997 GT3 RS",
    6,
    "0:11",
    "Porsche 997 GT3 RS.ogg",
  ],
  ["bmw-m3-gt2-2010", "BMW M3 GT2", 8, "0:20", "BMW M3 GT2 (2010).ogg"],
  ["audi-r8-lms-2010", "Audi R8 LMS", 10, "0:11", "Audi R8 LMS (2010).ogg"],
  ["ferrari-f430-2010", "Ferrari F430", 8, "0:24", "Ferrari F430 (2010).ogg"],
  [
    "audi-sport-quattro-s1-1985",
    "Audi Sport Quattro S1",
    5,
    "0:18",
    "Audi Sport Quattro S1 (1985).ogg",
  ],
  ["ford-rs200", "Ford RS200", 4, "0:17", "Ford RS200.ogg"],
  ["ac-cobra-1964", "AC Cobra (1964)", 8, "0:22", "AC Cobra (1964).ogg"],
];

const bySa3 = "https://creativecommons.org/licenses/by-sa/3.0/";

export const communitySounds = [
  ...edvvc.map(([id, title, cylinders, duration, file]) => ({
    id,
    title,
    cylinders,
    duration,
    file,
    audio: `${id}.ogg`,
    author: "Edvvc",
    license: "CC BY-SA 3.0",
    licenseUrl: bySa3,
  })),
  {
    id: "ferrari-f355-under-hood-exhaust-sound",
    title: "Ferrari F355 · under-hood exhaust",
    cylinders: 8,
    duration: "0:18",
    file: "Ferrari F355 under-hood exhaust sound.ogg",
    audio: "ferrari-f355-under-hood-exhaust-sound.ogg",
    author: "enginemusic",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
  },
  {
    id: "hr12de-march-k13",
    title: "Nissan March K13 · HR12DE",
    cylinders: 3,
    duration: "0:26",
    file: "HR12DE-March-K13.oga",
    audio: "hr12de-march-k13.ogg",
    author: "Oq10pass",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
  },
  {
    id: "open-corsa-e-model-2014-engine-startup-sound",
    title: "Opel Corsa E · engine start",
    cylinders: 4,
    duration: "0:04",
    file: "Open Corsa E model 2014 engine startup sound.ogg",
    audio: "open-corsa-e-model-2014-engine-startup-sound.ogg",
    author: "MKFI",
    license: "Public domain",
    licenseUrl:
      "https://commons.wikimedia.org/wiki/File:Open_Corsa_E_model_2014_engine_startup_sound.ogg",
  },
  {
    id: "lexus-is-f-dynamometer-2ur-gse-2008",
    title: "Lexus IS-F · 2UR-GSE dyno",
    cylinders: 8,
    duration: "0:15",
    file: "Lexus IS-F dynamometer 2UR-GSE (2008).ogg",
    audio: "lexus-is-f-dynamometer-2ur-gse-2008.ogg",
    author: "Altair78",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
  },
  {
    id: "lexus-lfa-revving-1lr-gue-2009",
    title: "Lexus LFA · 1LR-GUE rev",
    cylinders: 10,
    duration: "0:17",
    file: "Lexus LFA revving 1LR-GUE (2009).ogg",
    audio: "lexus-lfa-revving-1lr-gue-2009.ogg",
    author: "Altair78",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
  },
  {
    id: "maserati-granturismo-s-exhaust",
    title: "Maserati GranTurismo S · exhaust",
    cylinders: 8,
    duration: "1:06",
    file: "Maserati GranTurismo S Exhaust.ogg",
    audio: "maserati-granturismo-s-exhaust.ogg",
    author: "lmartins",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
  },
  {
    id: "scirocco-r-0",
    title: "Volkswagen Scirocco R",
    cylinders: 4,
    duration: "0:24",
    file: "Scirocco r 0.ogg",
    audio: "scirocco-r-0.ogg",
    author: "myvolkswagen",
    license: "Public domain",
    licenseUrl: "https://commons.wikimedia.org/wiki/File:Scirocco_r_0.ogg",
  },
  {
    id: "wws-volkswagenbeetle8211engine",
    title: "Volkswagen Beetle · engine",
    cylinders: 4,
    duration: "0:55",
    file: "WWS VolkswagenBeetle8211engine.ogg",
    audio: "wws-volkswagenbeetle8211engine.ogg",
    author: "Work With Sounds / Technical Museum of Slovenia",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
  },
] as const;
