import type { PhotoTarget } from "./types";

export const data = [
  {"key":"ch-lauterbrunnen","countryCode":"CH","region":"Lauterbrunnen","latitude":46.594,"longitude":7.908,"query":"Lauterbrunnen valley road automotive"},
  {"key":"at-grossglockner","countryCode":"AT","region":"Grossglockner","latitude":47.074,"longitude":12.842,"query":"Grossglockner alpine road sports car"},
  {"key":"at-silvretta","countryCode":"AT","region":"Silvretta","latitude":46.91,"longitude":10.095,"query":"Silvretta Austria mountain road car"},
  {"key":"at-wachau","countryCode":"AT","region":"Wachau Valley","latitude":48.36,"longitude":15.42,"query":"Wachau Austria river road classic car"},
  {"key":"at-salzkammergut","countryCode":"AT","region":"Salzkammergut","latitude":47.7,"longitude":13.48,"query":"Salzkammergut lake road automotive"},
  {"key":"si-vrsic","countryCode":"SI","region":"Vršič Pass","latitude":46.435,"longitude":13.744,"query":"Vrsic Pass Slovenia car road"},
  {"key":"si-soca","countryCode":"SI","region":"Soča Valley","latitude":46.337,"longitude":13.552,"query":"Soca Valley Slovenia scenic road car"},
  {"key":"hr-adriatic","countryCode":"HR","region":"Adriatic Highway","latitude":44.84,"longitude":14.9,"query":"Croatia Adriatic Highway sports car"},
  {"key":"hr-istria","countryCode":"HR","region":"Istria","latitude":45.24,"longitude":13.9,"query":"Istria Croatia scenic road car"},
  {"key":"hr-plitvice","countryCode":"HR","region":"Lika","latitude":44.88,"longitude":15.61,"query":"Croatia forest road automotive photography"},
  {"key":"me-kotor","countryCode":"ME","region":"Bay of Kotor","latitude":42.43,"longitude":18.77,"query":"Bay of Kotor Montenegro road car"},
  {"key":"me-durmitor","countryCode":"ME","region":"Durmitor","latitude":43.13,"longitude":19.02,"query":"Durmitor Montenegro mountain road automotive"},
  {"key":"al-logara","countryCode":"AL","region":"Llogara Pass","latitude":40.198,"longitude":19.593,"query":"Llogara Pass Albania sports car"},
  {"key":"al-komani","countryCode":"AL","region":"Albanian Alps","latitude":42.2,"longitude":19.82,"query":"Albanian Alps mountain road car"},
  {"key":"gr-meteora","countryCode":"GR","region":"Meteora","latitude":39.72,"longitude":21.63,"query":"Meteora Greece scenic road car"},
  {"key":"gr-mani","countryCode":"GR","region":"Mani Peninsula","latitude":36.69,"longitude":22.39,"query":"Mani Greece coastal road automotive"},
  {"key":"gr-pindus","countryCode":"GR","region":"Pindus Mountains","latitude":39.78,"longitude":21.18,"query":"Pindus Greece mountain road car"},
  {"key":"gr-crete","countryCode":"GR","region":"Crete","latitude":35.2,"longitude":24.9,"query":"Crete mountain coastal road car"},
  {"key":"ro-transfagarasan","countryCode":"RO","region":"Transfăgărășan","latitude":45.6,"longitude":24.62,"query":"Transfagarasan Romania sports car"},
  {"key":"ro-transalpina","countryCode":"RO","region":"Transalpina","latitude":45.36,"longitude":23.67,"query":"Transalpina Romania mountain road car"},
  {"key":"ro-bicaz","countryCode":"RO","region":"Bicaz Gorge","latitude":46.81,"longitude":25.82,"query":"Bicaz Gorge Romania road automotive"},
  {"key":"bg-shipka","countryCode":"BG","region":"Shipka Pass","latitude":42.75,"longitude":25.32,"query":"Shipka Pass Bulgaria scenic road car"},
  {"key":"bg-rhodope","countryCode":"BG","region":"Rhodope Mountains","latitude":41.68,"longitude":24.62,"query":"Rhodope Bulgaria mountain road automotive"},
  {"key":"rs-tara","countryCode":"RS","region":"Tara National Park","latitude":43.91,"longitude":19.37,"query":"Tara Serbia forest road car"},
  {"key":"ba-sarajevo-mountains","countryCode":"BA","region":"Sarajevo mountains","latitude":43.74,"longitude":18.28,"query":"Bosnia mountain road automotive photography"},
] satisfies readonly PhotoTarget[];
