import type { PhotoTarget } from "./types";

export const data = [
  {"key":"pt-lisbon-atlantic","countryCode":"PT","region":"Lisbon Atlantic coast","latitude":38.6968,"longitude":-9.4207,"query":"Lisbon Atlantic coastal road scenic car photography"},
  {"key":"pt-sintra","countryCode":"PT","region":"Sintra","latitude":38.8029,"longitude":-9.3817,"query":"Sintra Portugal forest road scenic automotive"},
  {"key":"pt-douro","countryCode":"PT","region":"Douro Valley","latitude":41.1621,"longitude":-7.7886,"query":"Douro Valley Portugal winding road car"},
  {"key":"pt-madeira","countryCode":"PT","region":"Madeira","latitude":32.7607,"longitude":-17.0203,"query":"Madeira mountain road scenic automotive"},
  {"key":"es-costa-brava","countryCode":"ES","region":"Costa Brava","latitude":41.8612,"longitude":3.1378,"query":"Costa Brava coastal road sports car"},
  {"key":"es-pyrenees","countryCode":"ES","region":"Spanish Pyrenees","latitude":42.5476,"longitude":0.1326,"query":"Spanish Pyrenees mountain pass car road"},
  {"key":"es-picos-europa","countryCode":"ES","region":"Picos de Europa","latitude":43.1872,"longitude":-4.8217,"query":"Picos de Europa scenic road automotive"},
  {"key":"es-basque-coast","countryCode":"ES","region":"Basque coast","latitude":43.3803,"longitude":-2.9872,"query":"Basque coast road Spain car photography"},
  {"key":"es-andalusia","countryCode":"ES","region":"Andalusian white villages","latitude":36.7415,"longitude":-5.1644,"query":"Andalusia white village mountain road car"},
  {"key":"es-tenerife","countryCode":"ES","region":"Tenerife","latitude":28.2723,"longitude":-16.6425,"query":"Tenerife volcanic road scenic car"},
  {"key":"fr-alps","countryCode":"FR","region":"French Alps","latitude":45.0535,"longitude":6.4076,"query":"French Alps mountain pass sports car"},
  {"key":"fr-provence","countryCode":"FR","region":"Provence","latitude":43.9493,"longitude":5.0628,"query":"Provence scenic road classic car"},
  {"key":"fr-corsica","countryCode":"FR","region":"Corsica","latitude":42.2584,"longitude":9.1501,"query":"Corsica coastal mountain road car"},
  {"key":"fr-brittany","countryCode":"FR","region":"Brittany coast","latitude":48.202,"longitude":-4.513,"query":"Brittany coast road automotive photography"},
  {"key":"fr-alsace","countryCode":"FR","region":"Alsace","latitude":48.125,"longitude":7.258,"query":"Alsace vineyard road classic car"},
  {"key":"fr-pyrenees","countryCode":"FR","region":"French Pyrenees","latitude":42.873,"longitude":0.145,"query":"French Pyrenees road sports car"},
  {"key":"de-black-forest","countryCode":"DE","region":"Black Forest","latitude":48.191,"longitude":8.195,"query":"Black Forest Germany road BMW photography"},
  {"key":"de-bavarian-alps","countryCode":"DE","region":"Bavarian Alps","latitude":47.5702,"longitude":11.0955,"query":"Bavarian Alps road German car"},
  {"key":"de-moselle","countryCode":"DE","region":"Moselle Valley","latitude":50.146,"longitude":7.166,"query":"Moselle Valley Germany road car"},
  {"key":"de-saxon-switzerland","countryCode":"DE","region":"Saxon Switzerland","latitude":50.913,"longitude":14.254,"query":"Saxon Switzerland scenic road automotive"},
  {"key":"de-baltic-coast","countryCode":"DE","region":"Baltic coast","latitude":54.384,"longitude":12.501,"query":"Germany Baltic coast road car photography"},
  {"key":"de-eifel","countryCode":"DE","region":"Eifel","latitude":50.3569,"longitude":6.9453,"query":"Eifel Germany winding road sports car"},
  {"key":"it-dolomites","countryCode":"IT","region":"Dolomites","latitude":46.5405,"longitude":11.817,"query":"Dolomites mountain pass sports car"},
  {"key":"it-tuscany","countryCode":"IT","region":"Tuscany","latitude":43.062,"longitude":11.558,"query":"Tuscany cypress road classic car"},
  {"key":"it-amalfi","countryCode":"IT","region":"Amalfi Coast","latitude":40.634,"longitude":14.603,"query":"Amalfi Coast road Italian car"},
] satisfies readonly PhotoTarget[];
