import type { PhotoTarget } from "./types";

export const data = [
  {"key":"it-etna","countryCode":"IT","region":"Mount Etna","latitude":37.751,"longitude":14.993,"query":"Etna volcanic road Sicily car"},
  {"key":"it-sardinia","countryCode":"IT","region":"Sardinia","latitude":40.245,"longitude":9.189,"query":"Sardinia coastal road sports car"},
  {"key":"it-lake-como","countryCode":"IT","region":"Lake Como","latitude":46.017,"longitude":9.257,"query":"Lake Como scenic road classic car"},
  {"key":"it-gran-sasso","countryCode":"IT","region":"Gran Sasso","latitude":42.442,"longitude":13.559,"query":"Gran Sasso mountain road automotive"},
  {"key":"gb-nc500","countryCode":"GB","region":"North Coast 500","latitude":58.281,"longitude":-4.479,"query":"North Coast 500 Scotland car road"},
  {"key":"gb-snowdonia","countryCode":"GB","region":"Snowdonia","latitude":53.068,"longitude":-4.077,"query":"Snowdonia Wales mountain road car"},
  {"key":"gb-lake-district","countryCode":"GB","region":"Lake District","latitude":54.46,"longitude":-3.088,"query":"Lake District road classic car"},
  {"key":"gb-peak-district","countryCode":"GB","region":"Peak District","latitude":53.35,"longitude":-1.82,"query":"Peak District moody road sports car"},
  {"key":"gb-cornwall","countryCode":"GB","region":"Cornwall","latitude":50.111,"longitude":-5.48,"query":"Cornwall coastal road car photography"},
  {"key":"ie-wild-atlantic","countryCode":"IE","region":"Wild Atlantic Way","latitude":53.972,"longitude":-10.079,"query":"Wild Atlantic Way scenic road car"},
  {"key":"gb-causeway-coast","countryCode":"GB","region":"Causeway Coast","latitude":55.21,"longitude":-6.58,"query":"Causeway Coast road Northern Ireland car"},
  {"key":"no-lofoten","countryCode":"NO","region":"Lofoten","latitude":68.208,"longitude":13.68,"query":"Lofoten Norway road automotive photography"},
  {"key":"no-atlanterhavsveien","countryCode":"NO","region":"Atlantic Ocean Road","latitude":63.017,"longitude":7.354,"query":"Atlantic Ocean Road Norway car"},
  {"key":"no-geiranger","countryCode":"NO","region":"Geiranger","latitude":62.101,"longitude":7.206,"query":"Geiranger Norway hairpin road car"},
  {"key":"no-senja","countryCode":"NO","region":"Senja","latitude":69.306,"longitude":17.547,"query":"Senja Norway scenic route car"},
  {"key":"se-lapland","countryCode":"SE","region":"Swedish Lapland","latitude":67.85,"longitude":18.75,"query":"Swedish Lapland road car photography"},
  {"key":"se-west-coast","countryCode":"SE","region":"Swedish west coast","latitude":58.36,"longitude":11.23,"query":"Sweden west coast road automotive"},
  {"key":"fi-lakeland","countryCode":"FI","region":"Finnish Lakeland","latitude":61.89,"longitude":28.75,"query":"Finnish Lakeland scenic road car"},
  {"key":"fi-lapland","countryCode":"FI","region":"Finnish Lapland","latitude":68.42,"longitude":27.42,"query":"Finnish Lapland road automotive"},
  {"key":"dk-jutland","countryCode":"DK","region":"West Jutland coast","latitude":56.16,"longitude":8.12,"query":"Denmark Jutland coastal road car"},
  {"key":"is-ring-road-south","countryCode":"IS","region":"South Iceland","latitude":63.56,"longitude":-18.25,"query":"Iceland ring road south car"},
  {"key":"is-westfjords","countryCode":"IS","region":"Westfjords","latitude":65.73,"longitude":-23.2,"query":"Iceland Westfjords road automotive"},
  {"key":"ch-furka","countryCode":"CH","region":"Furka Pass","latitude":46.572,"longitude":8.416,"query":"Furka Pass Switzerland sports car"},
  {"key":"ch-susten","countryCode":"CH","region":"Susten Pass","latitude":46.73,"longitude":8.45,"query":"Susten Pass Swiss Alps car"},
  {"key":"ch-julier","countryCode":"CH","region":"Julier Pass","latitude":46.47,"longitude":9.72,"query":"Julier Pass Switzerland road car"},
] satisfies readonly PhotoTarget[];
