import type { PhotoTarget } from "./types";

export const data = [
  {"key":"ba-una","countryCode":"BA","region":"Una Valley","latitude":44.74,"longitude":15.93,"query":"Una Bosnia scenic road car"},
  {"key":"mk-mavrovo","countryCode":"MK","region":"Mavrovo","latitude":41.66,"longitude":20.68,"query":"Mavrovo North Macedonia road car"},
  {"key":"nl-zeeland","countryCode":"NL","region":"Zeeland","latitude":51.65,"longitude":3.72,"query":"Zeeland Netherlands coastal road car"},
  {"key":"nl-veluwe","countryCode":"NL","region":"Veluwe","latitude":52.19,"longitude":5.83,"query":"Veluwe Netherlands forest road automotive"},
  {"key":"be-ardennes","countryCode":"BE","region":"Belgian Ardennes","latitude":50.25,"longitude":5.67,"query":"Belgian Ardennes winding road car"},
  {"key":"lu-mullerthal","countryCode":"LU","region":"Mullerthal","latitude":49.79,"longitude":6.31,"query":"Mullerthal Luxembourg scenic road car"},
  {"key":"ee-saaremaa","countryCode":"EE","region":"Saaremaa","latitude":58.38,"longitude":22.52,"query":"Saaremaa Estonia coastal road car"},
  {"key":"lv-gauja","countryCode":"LV","region":"Gauja","latitude":57.25,"longitude":24.95,"query":"Gauja Latvia forest road automotive"},
  {"key":"lt-curonian-spit","countryCode":"LT","region":"Curonian Spit","latitude":55.31,"longitude":21.01,"query":"Curonian Spit Lithuania road car"},
  {"key":"pl-tatra","countryCode":"PL","region":"Tatra Mountains","latitude":49.27,"longitude":19.98,"query":"Tatra Poland mountain road car"},
  {"key":"pl-bieszczady","countryCode":"PL","region":"Bieszczady","latitude":49.16,"longitude":22.48,"query":"Bieszczady Poland scenic road automotive"},
  {"key":"cz-bohemian-switzerland","countryCode":"CZ","region":"Bohemian Switzerland","latitude":50.86,"longitude":14.29,"query":"Bohemian Switzerland Czech road car"},
  {"key":"cz-sumava","countryCode":"CZ","region":"Šumava","latitude":49.05,"longitude":13.57,"query":"Sumava Czech forest road automotive"},
  {"key":"sk-high-tatras","countryCode":"SK","region":"High Tatras","latitude":49.16,"longitude":20.13,"query":"High Tatras Slovakia road car"},
  {"key":"hu-balaton","countryCode":"HU","region":"Lake Balaton","latitude":46.83,"longitude":17.73,"query":"Lake Balaton Hungary road classic car"},
  {"key":"cy-troodos","countryCode":"CY","region":"Troodos Mountains","latitude":34.93,"longitude":32.87,"query":"Troodos Cyprus mountain road car"},
  {"key":"mt-gozo","countryCode":"MT","region":"Gozo","latitude":36.05,"longitude":14.25,"query":"Gozo Malta coastal road automotive"},
  {"key":"tr-thrace-coast","countryCode":"TR","region":"Thrace coast","latitude":41.5,"longitude":28.01,"query":"Turkey Thrace coastal road car"},
  {"key":"tr-bosphorus-night","countryCode":"TR","region":"Istanbul","latitude":41.07,"longitude":29.04,"query":"Istanbul Bosphorus night car photography"},
  {"key":"ad-pyrenees","countryCode":"AD","region":"Andorran Pyrenees","latitude":42.54,"longitude":1.59,"query":"Andorra Pyrenees mountain road sports car"},
  {"key":"li-alpine-road","countryCode":"LI","region":"Liechtenstein Alps","latitude":47.12,"longitude":9.57,"query":"Liechtenstein alpine road car photography"},
  {"key":"sm-monte-titano","countryCode":"SM","region":"Monte Titano","latitude":43.94,"longitude":12.45,"query":"San Marino mountain road classic car"},
  {"key":"mc-riviera","countryCode":"MC","region":"Monaco Riviera","latitude":43.74,"longitude":7.43,"query":"Monaco Riviera road supercar photography"},
  {"key":"fo-streymoy","countryCode":"FO","region":"Streymoy","latitude":62.06,"longitude":-6.94,"query":"Faroe Islands scenic road car photography"},
  {"key":"md-codru","countryCode":"MD","region":"Codru","latitude":47.01,"longitude":28.52,"query":"Moldova countryside road classic car"},
] satisfies readonly PhotoTarget[];
