import type { ScoutSource } from "./types";

export const data = [
  {"key":"nurburgring","kind":"event_page","scope":"europe","name":"Nürburgring","url":"https://www.nuerburgring.de/events","countryCode":"DE"},
  {"key":"hockenheimring","kind":"event_page","scope":"europe","name":"Hockenheimring","url":"https://www.hockenheimring.de/events/","countryCode":"DE"},
  {"key":"lausitzring","kind":"event_page","scope":"europe","name":"DEKRA Lausitzring","url":"https://dekra-lausitzring.de/events/","countryCode":"DE"},
  {"key":"oschersleben","kind":"event_page","scope":"europe","name":"Motorsport Arena Oschersleben","url":"https://www.motorsportarena.com/Termine","countryCode":"DE"},
  {"key":"bilster-berg","kind":"event_page","scope":"europe","name":"Bilster Berg","url":"https://www.bilster-berg.de/veranstaltungen/","countryCode":"DE"},
  {"key":"spa-francorchamps","kind":"event_page","scope":"europe","name":"Circuit de Spa-Francorchamps","url":"https://www.spa-francorchamps.be/agenda","countryCode":"BE"},
  {"key":"zandvoort","kind":"event_page","scope":"europe","name":"Circuit Zandvoort","url":"https://www.circuitzandvoort.nl/en/calendar/","countryCode":"NL"},
  {"key":"silverstone","kind":"event_page","scope":"global_major","name":"Silverstone","url":"https://www.silverstone.co.uk/events","countryCode":"GB"},
  {"key":"goodwood","kind":"event_page","scope":"global_major","name":"Goodwood","url":"https://www.goodwood.com/motorsport/","countryCode":"GB"},
  {"key":"brands-hatch","kind":"event_page","scope":"europe","name":"Brands Hatch","url":"https://www.brandshatch.co.uk/calendar","countryCode":"GB"},
  {"key":"santa-pod","kind":"event_page","scope":"europe","name":"Santa Pod Raceway","url":"https://santapod.co.uk/calendar.php","countryCode":"GB"},
  {"key":"driftland","kind":"event_page","scope":"europe","name":"Driftland","url":"https://www.driftlanduk.com/events","countryCode":"GB"},
  {"key":"le-mans","kind":"event_page","scope":"global_major","name":"Circuit des 24 Heures du Mans","url":"https://www.lemans.org/en/calendar","countryCode":"FR"},
  {"key":"paul-ricard","kind":"event_page","scope":"europe","name":"Circuit Paul Ricard","url":"https://www.circuitpaulricard.com/en/events/","countryCode":"FR"},
  {"key":"magny-cours","kind":"event_page","scope":"europe","name":"Circuit de Nevers Magny-Cours","url":"https://www.circuitmagnycours.com/en/calendar/","countryCode":"FR"},
  {"key":"monza","kind":"event_page","scope":"global_major","name":"Autodromo Nazionale Monza","url":"https://www.monzanet.it/en/calendar/","countryCode":"IT"},
  {"key":"imola","kind":"event_page","scope":"global_major","name":"Autodromo di Imola","url":"https://www.autodromoimola.it/en/events/","countryCode":"IT"},
  {"key":"mugello","kind":"event_page","scope":"europe","name":"Mugello Circuit","url":"https://www.mugellocircuit.com/en/events.html","countryCode":"IT"},
  {"key":"misano","kind":"event_page","scope":"europe","name":"Misano World Circuit","url":"https://www.misanocircuit.com/calendario-eventi/","countryCode":"IT"},
  {"key":"red-bull-ring","kind":"event_page","scope":"global_major","name":"Red Bull Ring","url":"https://www.redbullring.com/en/events-tickets/","countryCode":"AT"},
  {"key":"barcelona-catalunya","kind":"event_page","scope":"global_major","name":"Circuit de Barcelona-Catalunya","url":"https://www.circuitcat.com/en/calendar/","countryCode":"ES"},
  {"key":"portimao","kind":"event_page","scope":"europe","name":"Autódromo Internacional do Algarve","url":"https://autodromodoalgarve.com/calendar/","countryCode":"PT"},
  {"key":"estoril","kind":"event_page","scope":"europe","name":"Circuito Estoril","url":"https://www.circuito-estoril.pt/en/events/","countryCode":"PT"},
  {"key":"hungaroring","kind":"event_page","scope":"global_major","name":"Hungaroring","url":"https://hungaroring.hu/site/en/races","countryCode":"HU"},
  {"key":"brno-circuit","kind":"event_page","scope":"europe","name":"Automotodrom Brno","url":"https://www.automotodrombrno.cz/en/calendar/","countryCode":"CZ"},
] satisfies readonly ScoutSource[];
