begin;

-- Curated Roadbook discovery set: two user-supplied images and 25 free
-- Unsplash images. Remote images retain their photographer/source metadata.
-- Representative imagery is labelled in the UI and never presented as proof
-- of a venue's current access or operating conditions.
alter table public.roadbook_venues
  drop constraint if exists roadbook_venues_category_check;

alter table public.roadbook_venues
  add constraint roadbook_venues_category_check check (category in (
    'drift_circuit', 'drag_acceleration', 'track_day',
    'proving_ground', 'scenic_route', 'autobahn_context', 'car_photo_spot'
  ));

alter table public.roadbook_venues
  drop constraint if exists roadbook_photo_spot_public_access_check;

alter table public.roadbook_venues
  add constraint roadbook_photo_spot_public_access_check check (
    category <> 'car_photo_spot' or access_status in ('public_context', 'permit_required')
  );

alter table public.roadbook_venues
  drop constraint if exists roadbook_photo_spot_published_details_check;

alter table public.roadbook_venues
  add constraint roadbook_photo_spot_published_details_check check (
    category <> 'car_photo_spot' or not published or coalesce((
      jsonb_typeof(requirements -> 'photo_spot') = 'object'
      and jsonb_typeof(requirements #> '{photo_spot,visualDescription}') = 'string'
      and jsonb_typeof(requirements #> '{photo_spot,bestTime}') = 'string'
      and jsonb_typeof(requirements #> '{photo_spot,lighting}') = 'string'
      and jsonb_typeof(requirements #> '{photo_spot,parkingAccess}') = 'string'
      and jsonb_typeof(requirements #> '{photo_spot,permissionRequired}') = 'boolean'
      and jsonb_typeof(requirements #> '{photo_spot,vehicleSuitability}') = 'string'
      and jsonb_typeof(requirements #> '{photo_spot,safetyNotes}') = 'string'
    ), false)
  );

alter table public.roadbook_events
  add column if not exists all_day boolean not null default false;

insert into public.roadbook_venues (
  name, slug, category, description, access_status, location, country_code, city,
  surface, source_label, source_url, verification_status, booking_url,
  route_geometry, requirements, published
)
values
  ('Tunitas Creek car photo spot', 'tunitas-creek-car-photo', 'car_photo_spot', 'A forest-side automotive photography reference on Tunitas Creek Road. Stop only in a legal pull-off and verify current access before setting up.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(-122.324, 37.383), 4326)::extensions.geography, 'US', 'Woodside', 'Paved road', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=37.383&mlon=-122.324#map=14/37.383/-122.324', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"/roadbook/places/tunitas-creek-bmw.webp","alt":"Black BMW photographed among tall forest trees","photographer":"User-supplied reference","sourceUrl":"https://capcar.dev/roadbook","license":"User supplied for CapCar","context":"location"},"photo_spot":{"visualDescription":"Dense forest, deep greens and filtered light around a classic saloon.","bestTime":"Late afternoon when light reaches through the trees","lighting":"Soft side light through the forest canopy","parkingAccess":"Use legal pull-offs only; do not stop in the carriageway","permissionRequired":false,"vehicleSuitability":"Road-legal passenger cars","safetyNotes":"Keep the road clear and confirm local parking restrictions.","tags":["forest"]}}'::jsonb, true),
  ('Snake Pass forest atmosphere', 'snake-pass-forest-atmosphere', 'scenic_route', 'A moody Peak District driving reference. The supplied forest-road photograph is representative; weather, closures and safe stopping points must be checked before travel.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(-1.858, 53.432), 4326)::extensions.geography, 'GB', 'Peak District', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=53.432&mlon=-1.858#map=12/53.432/-1.858', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"/roadbook/places/english-forest-road.webp","alt":"Misty forest road disappearing between dark green trees","photographer":"Danis Lou · user-supplied reference","sourceUrl":"https://capcar.dev/roadbook","license":"User supplied for CapCar","context":"representative"}}'::jsonb, true),
  ('Passo Pordoi', 'passo-pordoi', 'scenic_route', 'A Dolomites mountain-pass drive near Canazei. Check seasonal conditions, closures and safe viewpoints before setting out.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(11.812, 46.487), 4326)::extensions.geography, 'IT', 'Canazei', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=46.487&mlon=11.812#map=13/46.487/11.812', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1753978103194-1e02e091039a?auto=format&fit=crop&w=1200&q=78","alt":"Mountain road and dramatic Dolomites near Canazei","photographer":"Tarik Caramanico","sourceUrl":"https://unsplash.com/photos/PxVr3PjloiI","license":"Unsplash License","context":"location"}}'::jsonb, true),
  ('Furka Pass · Belvédère bend', 'furka-pass-belvedere-bend', 'car_photo_spot', 'A high-alpine photo stop near the historic Belvédère curve. Access is seasonal and stopping must remain inside designated areas.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(8.387, 46.576), 4326)::extensions.geography, 'CH', 'Obergoms', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=46.576&mlon=8.387#map=15/46.576/8.387', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1773869910099-cde5de88a71a?auto=format&fit=crop&w=1200&q=78","alt":"Historic hotel beside a sweeping bend on Furka Pass","photographer":"Markus McKay","sourceUrl":"https://unsplash.com/photos/bjSchO7WlHg","license":"Unsplash License","context":"location"},"photo_spot":{"visualDescription":"High-alpine switchback with stone architecture and a layered mountain backdrop.","bestTime":"Early morning outside peak traffic","lighting":"Morning side light across the bend","parkingAccess":"Use designated parking only","permissionRequired":false,"vehicleSuitability":"Road-legal passenger cars","safetyNotes":"The pass is seasonal; never stand or park in the live road.","tags":["mountain","sunrise","architecture"]}}'::jsonb, true),
  ('Lauterbrunnen valley approach', 'lauterbrunnen-valley-approach', 'scenic_route', 'A scenic valley approach framed by cliffs and waterfalls. Local access, traffic and parking rules take priority.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(7.909, 46.594), 4326)::extensions.geography, 'CH', 'Lauterbrunnen', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=46.594&mlon=7.909#map=13/46.594/7.909', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1762380764537-4018d2fae372?auto=format&fit=crop&w=1200&q=78","alt":"Road through the Lauterbrunnen valley beneath steep mountains","photographer":"Thierry Lemaitre","sourceUrl":"https://unsplash.com/photos/0kmP2q-Pd7A","license":"Unsplash License","context":"location"}}'::jsonb, true),
  ('Julier Pass', 'julier-pass', 'scenic_route', 'A broad Swiss alpine crossing between the Engadin and central Graubünden. Check weather and seasonal road conditions.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(9.727, 46.471), 4326)::extensions.geography, 'CH', 'Bivio', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=46.471&mlon=9.727#map=13/46.471/9.727', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1759334464603-7b15d5ae95a8?auto=format&fit=crop&w=1200&q=78","alt":"Alpine road crossing the open landscape of Julier Pass","photographer":"Tamara Menzi","sourceUrl":"https://unsplash.com/photos/fEiKgEBXb5I","license":"Unsplash License","context":"location"}}'::jsonb, true),
  ('Amalfi Coast · SS163', 'amalfi-coast-ss163', 'scenic_route', 'A coastal route with tight bends, villages and sea views. Traffic restrictions and parking rules can change seasonally.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(14.602, 40.633), 4326)::extensions.geography, 'IT', 'Amalfi', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=40.633&mlon=14.602#map=13/40.633/14.602', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1780558143087-c60c284a3ccb?auto=format&fit=crop&w=1200&q=78","alt":"Sunlit coastal road above the Mediterranean near Amalfi","photographer":"Ahmet Yüksek","sourceUrl":"https://unsplash.com/photos/5XEuMa05B64","license":"Unsplash License","context":"location"}}'::jsonb, true),
  ('Furka Pass · Realp approach', 'furka-pass-realp-approach', 'scenic_route', 'The eastern approach to Furka Pass from Realp. The road is seasonal; check official closures and conditions.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(8.503, 46.598), 4326)::extensions.geography, 'CH', 'Realp', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=46.598&mlon=8.503#map=13/46.598/8.503', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1689696404387-61b34fe2fc64?auto=format&fit=crop&w=1200&q=78","alt":"Mountain road climbing from Realp toward Furka Pass","photographer":"Milosz Roman","sourceUrl":"https://unsplash.com/photos/4bQ6g9RhQuc","license":"Unsplash License","context":"location"}}'::jsonb, true),
  ('Rhein-Neckar industrial overlook', 'rhein-neckar-industrial-overlook', 'car_photo_spot', 'An elevated industrial landscape reference in the Rhein-Neckar region. Confirm the exact parking and access rules on arrival.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(8.457, 49.488), 4326)::extensions.geography, 'DE', 'Mannheim', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=49.488&mlon=8.457#map=13/49.488/8.457', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1738996596694-93a6a2359b22?auto=format&fit=crop&w=1200&q=78","alt":"Aerial industrial landscape in the Rhein-Neckar region","photographer":"Bernd Dittrich","sourceUrl":"https://unsplash.com/photos/MtpoxoKjzog","license":"Unsplash License","context":"location"},"photo_spot":{"visualDescription":"Industrial geometry, rail lines and broad urban texture for contextual automotive frames.","bestTime":"Blue hour or clear late afternoon","lighting":"Open sky with strong directional light","parkingAccess":"Use public parking and pedestrian viewpoints only","permissionRequired":false,"vehicleSuitability":"Road-legal passenger cars","safetyNotes":"Do not enter rail, port or industrial property.","tags":["industrial","urban"]}}'::jsonb, true),
  ('Stuttgart night architecture', 'stuttgart-night-architecture', 'car_photo_spot', 'A central Stuttgart night-photo reference with modern architecture and city light. Use legal parking and keep pedestrian routes clear.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(9.18, 48.779), 4326)::extensions.geography, 'DE', 'Stuttgart', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=48.779&mlon=9.180#map=14/48.779/9.180', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1624607391688-066cfc6fafc4?auto=format&fit=crop&w=1200&q=78","alt":"Modern Stuttgart architecture illuminated at night","photographer":"Christian Lue","sourceUrl":"https://unsplash.com/photos/wPDCjEgsLJ0","license":"Unsplash License","context":"location"},"photo_spot":{"visualDescription":"Clean city lines, glass façades and controlled pools of artificial light.","bestTime":"Blue hour through early night","lighting":"Mixed architectural and street lighting","parkingAccess":"Public car parks only; shoot from pedestrian areas","permissionRequired":false,"vehicleSuitability":"Road-legal passenger cars","safetyNotes":"Avoid loading bays, taxi ranks and active traffic lanes.","tags":["architecture","night","urban"]}}'::jsonb, true),
  ('Driftland', 'driftland', 'drift_circuit', 'A dedicated Scottish drift venue. Driver access, noise limits and event eligibility are controlled by the operator.', 'permit_required', extensions.st_setsrid(extensions.st_makepoint(-3.179, 56.212), 4326)::extensions.geography, 'GB', 'Lochgelly', 'Asphalt', 'Driftland official website', 'https://www.driftlanduk.com/', 'official_source', 'https://www.driftlanduk.com/', null, '{"requiresRoadLegal":false,"hero_image":{"url":"https://images.unsplash.com/photo-1628706257660-69da3e1846a8?auto=format&fit=crop&w=1200&q=78","alt":"BMW drifting on a closed circuit with tyre smoke","photographer":"Niklas Bischop","sourceUrl":"https://unsplash.com/photos/MgeUfyj3bfg","license":"Unsplash License","context":"representative"}}'::jsonb, true),
  ('Nürburgring', 'nuerburgring', 'track_day', 'Motorsport venue and driving-event context. Check the official event and access information before travelling.', 'permit_required', extensions.st_setsrid(extensions.st_makepoint(6.9475, 50.3356), 4326)::extensions.geography, 'DE', 'Nürburg', 'Asphalt', 'Nürburgring official website', 'https://www.nuerburgring.de/', 'official_source', 'https://www.nuerburgring.de/', null, '{"requiresRoadLegal":false,"hero_image":{"url":"https://images.unsplash.com/photo-1690811260724-3986f44bff75?auto=format&fit=crop&w=1200&q=78","alt":"GT car attacking a corner at the Nürburgring","photographer":"Benoit Fraikin","sourceUrl":"https://unsplash.com/photos/pOliXRjusdw","license":"Unsplash License","context":"location"}}'::jsonb, true),
  ('Circuit de Spa-Francorchamps', 'circuit-spa-francorchamps', 'track_day', 'Permanent Belgian circuit. Public access, driving sessions and event entry are governed by the official calendar and organiser conditions.', 'permit_required', extensions.st_setsrid(extensions.st_makepoint(5.9714, 50.4372), 4326)::extensions.geography, 'BE', 'Stavelot', 'Asphalt', 'Circuit de Spa-Francorchamps official website', 'https://www.spa-francorchamps.be/', 'official_source', 'https://www.spa-francorchamps.be/', null, '{"requiresRoadLegal":false,"hero_image":{"url":"https://images.unsplash.com/photo-1698753047029-05b3011609b7?auto=format&fit=crop&w=1200&q=78","alt":"Race cars on circuit at Spa-Francorchamps","photographer":"Appic","sourceUrl":"https://unsplash.com/photos/Y__ZYcowSo0","license":"Unsplash License","context":"location"}}'::jsonb, true),
  ('Circuit de Nevers Magny-Cours', 'circuit-nevers-magny-cours', 'track_day', 'French permanent circuit with events and scheduled driving programmes. Check the operator calendar before travelling.', 'permit_required', extensions.st_setsrid(extensions.st_makepoint(3.164, 46.864), 4326)::extensions.geography, 'FR', 'Magny-Cours', 'Asphalt', 'Circuit de Nevers Magny-Cours official website', 'https://www.circuitmagnycours.com/', 'official_source', 'https://www.circuitmagnycours.com/', null, '{"requiresRoadLegal":false,"hero_image":{"url":"https://images.unsplash.com/photo-1685978995072-becd2fe95e83?auto=format&fit=crop&w=1200&q=78","alt":"Race car driving on circuit at Magny-Cours","photographer":"Nicolas Peyrol","sourceUrl":"https://unsplash.com/photos/bWeIfIhn4Pw","license":"Unsplash License","context":"location"}}'::jsonb, true),
  ('Transfăgărășan · North Gate', 'transfagarasan-north-gate', 'scenic_route', 'The northern approach to Romania''s DN7C mountain road. It is seasonal and can close for snow or severe weather.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(24.62, 45.6), 4326)::extensions.geography, 'RO', 'Cârțișoara', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=45.600&mlon=24.620#map=12/45.600/24.620', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1668682481807-4d3f15bb6ce4?auto=format&fit=crop&w=1200&q=78","alt":"Snow-covered Transfăgărășan mountain road","photographer":"Dan Cristian","sourceUrl":"https://unsplash.com/photos/kpxXwKZiEzg","license":"Unsplash License","context":"location"}}'::jsonb, true),
  ('Transfăgărășan · Forest ascent', 'transfagarasan-forest-ascent', 'scenic_route', 'A forested DN7C approach before the high alpine section. Check closures, weather and safe stopping points.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(24.633, 45.424), 4326)::extensions.geography, 'RO', 'Arefu', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=45.424&mlon=24.633#map=12/45.424/24.633', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1674142294682-f2a36fb9ba1e?auto=format&fit=crop&w=1200&q=78","alt":"Car driving through the green forest section of Transfăgărășan","photographer":"Fermoar.ro","sourceUrl":"https://unsplash.com/photos/x5dqW4AlQLM","license":"Unsplash License","context":"location"}}'::jsonb, true),
  ('Transfăgărășan · Arefu hairpins', 'transfagarasan-arefu-hairpins', 'car_photo_spot', 'A high viewpoint over the famous DN7C hairpins. Use established viewpoints and keep clear of the live road.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(24.638, 45.421), 4326)::extensions.geography, 'RO', 'Arefu', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=45.421&mlon=24.638#map=14/45.421/24.638', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1526112982068-f899a62e118e?auto=format&fit=crop&w=1200&q=78","alt":"Aerial view of the Transfăgărășan hairpins through the mountains","photographer":"Calin Stan","sourceUrl":"https://unsplash.com/photos/dHRopH1O8uY","license":"Unsplash License","context":"location"},"photo_spot":{"visualDescription":"Layered switchbacks and dark pine forest seen from above.","bestTime":"Morning before the road becomes busy","lighting":"Open mountain light; cloud can change quickly","parkingAccess":"Use marked viewpoints and parking areas only","permissionRequired":false,"vehicleSuitability":"Road-legal passenger cars","safetyNotes":"Stay behind barriers and never stand in the carriageway.","tags":["mountain","forest"]}}'::jsonb, true),
  ('Transfăgărășan · convoy viewpoint', 'transfagarasan-convoy-viewpoint', 'car_photo_spot', 'A mountain-road viewpoint suited to group and rolling-road context shots when traffic and parking conditions allow.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(24.626, 45.585), 4326)::extensions.geography, 'RO', 'Cârțișoara', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=45.585&mlon=24.626#map=14/45.585/24.626', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1674142293954-861bab025336?auto=format&fit=crop&w=1200&q=78","alt":"Cars travelling together on the Transfăgărășan mountain road","photographer":"Fermoar.ro","sourceUrl":"https://unsplash.com/photos/WMXAbpQJ2wA","license":"Unsplash License","context":"location"},"photo_spot":{"visualDescription":"Mountain road, rock faces and multiple cars framed through the bends.","bestTime":"Early morning in the open season","lighting":"Morning light from the east","parkingAccess":"Designated viewpoints only","permissionRequired":false,"vehicleSuitability":"Road-legal passenger cars","safetyNotes":"No rolling photography from unsafe positions; obey all traffic rules.","tags":["mountain","sunrise"]}}'::jsonb, true),
  ('Transfăgărășan · forest top-down', 'transfagarasan-forest-top-down', 'car_photo_spot', 'A forest-road composition reference for drone-style top-down framing. Drone operation requires separate legal checks and permission.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(24.648, 45.39), 4326)::extensions.geography, 'RO', 'Arefu', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=45.390&mlon=24.648#map=13/45.390/24.648', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1700692955799-c23fe7c85159?auto=format&fit=crop&w=1200&q=78","alt":"Top-down view of a road cutting through autumn forest","photographer":"Simon Fevery","sourceUrl":"https://unsplash.com/photos/5zha0r-8ruk","license":"Unsplash License","context":"location"},"photo_spot":{"visualDescription":"A narrow ribbon of tarmac enclosed by autumn forest canopy.","bestTime":"Autumn daylight","lighting":"Diffuse overhead light","parkingAccess":"Use legal parking away from the roadway","permissionRequired":true,"vehicleSuitability":"Road-legal passenger cars","safetyNotes":"Check local drone restrictions and never fly over traffic without authorization.","tags":["forest"]}}'::jsonb, true),
  ('Straße des 17. Juni', 'strasse-des-17-juni-photo', 'car_photo_spot', 'A broad Berlin boulevard with long axial views. Stopping and photography are limited by city traffic and event restrictions.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(13.35, 52.514), 4326)::extensions.geography, 'DE', 'Berlin', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=52.514&mlon=13.350#map=15/52.514/13.350', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1666809565537-51a65c56f09e?auto=format&fit=crop&w=1200&q=78","alt":"Cars on the tree-lined Straße des 17. Juni in Berlin","photographer":"Klarin Steffens","sourceUrl":"https://unsplash.com/photos/JmJQwU7i4Fo","license":"Unsplash License","context":"location"},"photo_spot":{"visualDescription":"Long central perspective, mature trees and recognizable Berlin city context.","bestTime":"Early Sunday morning when traffic is lighter","lighting":"Low-angle morning light along the boulevard","parkingAccess":"Use legal side-street or public parking only","permissionRequired":false,"vehicleSuitability":"Road-legal passenger cars","safetyNotes":"Do not stop in traffic lanes, bus zones or event-controlled areas.","tags":["urban","architecture","sunrise"]}}'::jsonb, true),
  ('Großglockner · Fuscher Törl', 'grossglockner-fuscher-toerl', 'scenic_route', 'A high-alpine section of the Großglockner road. The road is tolled and seasonal; check the operator before travel.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(12.829, 47.116), 4326)::extensions.geography, 'AT', 'Fusch', 'Asphalt', 'Grossglockner High Alpine Road official website', 'https://www.grossglockner.at/', 'official_source', 'https://www.grossglockner.at/', null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1698077326553-32c42f839a85?auto=format&fit=crop&w=1200&q=78","alt":"Vehicles rounding an alpine bend on the Großglockner road","photographer":"Unsplash contributor","sourceUrl":"https://unsplash.com/photos/T2kGcCcN6Sk","license":"Unsplash License","context":"location"}}'::jsonb, true),
  ('Großglockner · Edelweissspitze', 'grossglockner-edelweissspitze-photo', 'car_photo_spot', 'A high viewpoint above the Großglockner road. Parking is limited and the access road is narrow and seasonal.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(12.831, 47.123), 4326)::extensions.geography, 'AT', 'Fusch', 'Asphalt', 'Grossglockner High Alpine Road official website', 'https://www.grossglockner.at/', 'official_source', 'https://www.grossglockner.at/', null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1690818723690-2392147543e2?auto=format&fit=crop&w=1200&q=78","alt":"Red hatchback parked against a Großglockner mountain backdrop","photographer":"Nejc Soklič","sourceUrl":"https://unsplash.com/photos/bcK6c3h7osw","license":"Unsplash License","context":"location"},"photo_spot":{"visualDescription":"Open alpine panorama with rock, meadow and large mountain scale behind the car.","bestTime":"Early morning after the road opens","lighting":"Clear morning side light","parkingAccess":"Use signed bays only; space is limited","permissionRequired":false,"vehicleSuitability":"Road-legal cars suitable for steep alpine roads","safetyNotes":"Check opening, weather and tyre condition before the climb.","tags":["mountain","sunrise"]}}'::jsonb, true),
  ('Aschaffenburg golden-hour road', 'aschaffenburg-golden-hour-road', 'car_photo_spot', 'An urban-edge golden-hour reference near Aschaffenburg. Confirm the exact stopping point and local restrictions before shooting.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(9.152, 49.977), 4326)::extensions.geography, 'DE', 'Aschaffenburg', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=49.977&mlon=9.152#map=13/49.977/9.152', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1658792953215-6f5eee7ba26a?auto=format&fit=crop&w=1200&q=78","alt":"Classic car driving near Aschaffenburg in warm evening light","photographer":"Aravind Gopinath","sourceUrl":"https://unsplash.com/photos/pm1704Hc4_c","license":"Unsplash License","context":"location"},"photo_spot":{"visualDescription":"Warm sunset light, open tarmac and a restrained urban backdrop.","bestTime":"Golden hour before sunset","lighting":"Low warm backlight","parkingAccess":"Use legal parking away from through traffic","permissionRequired":false,"vehicleSuitability":"Road-legal passenger cars","safetyNotes":"Do not shoot from the live carriageway.","tags":["sunset","urban"]}}'::jsonb, true),
  ('Großglockner · Hochtor', 'grossglockner-hochtor', 'scenic_route', 'A dramatic high point on the Großglockner High Alpine Road. Toll, seasonal opening and weather restrictions apply.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(12.842, 47.084), 4326)::extensions.geography, 'AT', 'Heiligenblut', 'Asphalt', 'Grossglockner High Alpine Road official website', 'https://www.grossglockner.at/', 'official_source', 'https://www.grossglockner.at/', null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1485684884494-0149f7871a49?auto=format&fit=crop&w=1200&q=78","alt":"Mountain road beneath cloud at Großglockner","photographer":"Karsten Würth","sourceUrl":"https://unsplash.com/photos/8FLpwPwfYUs","license":"Unsplash License","context":"location"}}'::jsonb, true),
  ('Munich moody drive', 'munich-moody-drive', 'car_photo_spot', 'A representative Munich driving image for low-key automotive storytelling. Select a legal stationary viewpoint before taking photographs.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(11.582, 48.135), 4326)::extensions.geography, 'DE', 'Munich', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=48.135&mlon=11.582#map=13/48.135/11.582', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1596649714492-a8f90ecb3776?auto=format&fit=crop&w=1200&q=78","alt":"Driver view from a performance car on a moody Munich road","photographer":"Stephan Mahlke","sourceUrl":"https://unsplash.com/photos/fpgKH45Y6IQ","license":"Unsplash License","context":"representative"},"photo_spot":{"visualDescription":"Dark cockpit and road atmosphere suited to in-car detail storytelling.","bestTime":"Overcast daylight or blue hour","lighting":"Soft exterior light with instrument glow","parkingAccess":"Create stationary images only from legal parking","permissionRequired":false,"vehicleSuitability":"Road-legal passenger cars","safetyNotes":"A passenger or a fixed camera must handle any permitted moving capture; the driver must not operate a camera.","tags":["urban","night"]}}'::jsonb, true),
  ('Schwarzwaldhochstraße · B500', 'schwarzwaldhochstrasse-b500', 'scenic_route', 'A Black Forest driving route between Baden-Baden and Freudenstadt. Check weather, road works and seasonal traffic.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(8.23, 48.66), 4326)::extensions.geography, 'DE', 'Baden-Baden', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=48.660&mlon=8.230#map=11/48.660/8.230', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1675172299802-1e8359ee32ac?auto=format&fit=crop&w=1200&q=78","alt":"Road winding through the Black Forest landscape","photographer":"Markus McKay","sourceUrl":"https://unsplash.com/photos/bNUDo1z3mGY","license":"Unsplash License","context":"representative"}}'::jsonb, true),
  ('Odenwald · Abtsteinach', 'odenwald-abtsteinach', 'scenic_route', 'A quiet Odenwald road context near Abtsteinach. Follow posted limits and avoid peak recreational traffic.', 'public_context', extensions.st_setsrid(extensions.st_makepoint(8.78, 49.54), 4326)::extensions.geography, 'DE', 'Abtsteinach', 'Asphalt', 'OpenStreetMap location context', 'https://www.openstreetmap.org/?mlat=49.540&mlon=8.780#map=12/49.540/8.780', 'community_report', null, null, '{"requiresRoadLegal":true,"hero_image":{"url":"https://images.unsplash.com/photo-1728853832184-745b843a69b9?auto=format&fit=crop&w=1200&q=78","alt":"Curving rural road near Abtsteinach in the Odenwald","photographer":"Bernd Dittrich","sourceUrl":"https://unsplash.com/photos/I8-mLrW6rYM","license":"Unsplash License","context":"location"}}'::jsonb, true),
  ('Santa Pod Raceway', 'santa-pod-raceway', 'drag_acceleration', 'A dedicated drag-racing venue in England. Timed acceleration is permitted only in operator-run sessions under published rules.', 'permit_required', extensions.st_setsrid(extensions.st_makepoint(-0.599, 52.234), 4326)::extensions.geography, 'GB', 'Podington', 'Asphalt', 'Santa Pod Raceway official website', 'https://santapod.co.uk/', 'official_source', 'https://santapod.co.uk/', null, '{"requiresRoadLegal":false,"hero_image":{"url":"https://images.unsplash.com/photo-1698753047029-05b3011609b7?auto=format&fit=crop&w=1200&q=78","alt":"Performance cars on a closed racing circuit","photographer":"Appic","sourceUrl":"https://unsplash.com/photos/Y__ZYcowSo0","license":"Unsplash License","context":"representative"}}'::jsonb, true),
  ('Tierp Arena', 'tierp-arena', 'drag_acceleration', 'A Swedish motorsport arena known for drag racing. Driver participation and public access depend on the official programme.', 'permit_required', extensions.st_setsrid(extensions.st_makepoint(17.513, 60.345), 4326)::extensions.geography, 'SE', 'Tierp', 'Asphalt', 'Tierp Arena official website', 'https://tierparena.com/', 'official_source', 'https://tierparena.com/', null, '{"requiresRoadLegal":false,"hero_image":{"url":"https://images.unsplash.com/photo-1685978995072-becd2fe95e83?auto=format&fit=crop&w=1200&q=78","alt":"Competition car on a closed motorsport circuit","photographer":"Nicolas Peyrol","sourceUrl":"https://unsplash.com/photos/bWeIfIhn4Pw","license":"Unsplash License","context":"representative"}}'::jsonb, true)
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  access_status = excluded.access_status,
  location = excluded.location,
  country_code = excluded.country_code,
  city = excluded.city,
  surface = excluded.surface,
  source_label = excluded.source_label,
  source_url = excluded.source_url,
  verification_status = excluded.verification_status,
  booking_url = excluded.booking_url,
  requirements = excluded.requirements,
  published = true,
  updated_at = now();

insert into public.roadbook_events (
  venue_id, title, slug, description, event_type, participation,
  booking_required, starts_at, ends_at, booking_url, source_label, source_url,
  verification_status, verified_at, published, all_day
)
select
  v.id, seed.title, seed.slug, seed.description, seed.event_type,
  seed.participation, seed.booking_required, seed.starts_at, seed.ends_at,
  seed.booking_url, seed.source_label, seed.source_url,
  'official_source', now(), true, true
from (
  values
  ('nuerburgring', 'ADAC Racing Weekend', 'nuerburgring-adac-racing-weekend-2026', 'Officially listed motorsport weekend at the Nürburgring.', 'motorsport', 'spectator', false, timestamptz '2026-10-16 00:00:00+02', timestamptz '2026-10-18 23:59:59+02', null, 'Nürburgring official calendar', 'https://www.nuerburgring.de/events'),
  ('nuerburgring', 'RCN season finale', 'nuerburgring-rcn-season-finale-2026', 'Officially listed RCN season finale. Check the final timetable before travelling.', 'motorsport', 'spectator', false, timestamptz '2026-10-24 00:00:00+02', timestamptz '2026-10-24 23:59:59+02', null, 'Nürburgring official calendar', 'https://www.nuerburgring.de/events'),
  ('nuerburgring', 'Nürburgring Family Day', 'nuerburgring-family-day-2026', 'Official venue family day; activities and access follow the published programme.', 'festival', 'spectator', false, timestamptz '2026-10-25 00:00:00+02', timestamptz '2026-10-25 23:59:59+01', null, 'Nürburgring official calendar', 'https://www.nuerburgring.de/events'),
  ('hockenheimring', 'DTM Finale', 'hockenheimring-dtm-finale-2026', 'Officially listed DTM finale weekend at Hockenheimring.', 'motorsport', 'spectator', true, timestamptz '2026-10-09 00:00:00+02', timestamptz '2026-10-11 23:59:59+02', 'https://www.hockenheimring.de/', 'Hockenheimring official calendar', 'https://www.hockenheimring.de/events/'),
  ('hockenheimring', 'e4 TESTIVAL', 'hockenheimring-e4-testival-2026', 'Officially listed electric-mobility test and experience event.', 'festival', 'mixed', true, timestamptz '2026-10-16 00:00:00+02', timestamptz '2026-10-18 23:59:59+02', 'https://www.hockenheimring.de/', 'Hockenheimring official calendar', 'https://www.hockenheimring.de/events/'),
  ('santa-pod-raceway', 'JapShow Finale', 'santa-pod-japshow-finale-2026', 'Officially listed Japanese performance-car show and drag-racing event.', 'festival', 'mixed', true, timestamptz '2026-10-11 00:00:00+01', timestamptz '2026-10-11 23:59:59+01', 'https://santapod.co.uk/', 'Santa Pod official calendar', 'https://santapod.co.uk/calendar.php'),
  ('santa-pod-raceway', 'Flame & Thunder', 'santa-pod-flame-thunder-2026', 'Officially listed end-of-season motorsport and entertainment event.', 'festival', 'spectator', true, timestamptz '2026-10-31 00:00:00+00', timestamptz '2026-10-31 23:59:59+00', 'https://santapod.co.uk/', 'Santa Pod official calendar', 'https://santapod.co.uk/calendar.php'),
  ('santa-pod-raceway', 'Public Track Day', 'santa-pod-public-track-day-2026-11-01', 'Operator-listed public track day. Confirm vehicle eligibility and booking before travel.', 'track_day', 'driver', true, timestamptz '2026-11-01 00:00:00+00', timestamptz '2026-11-01 23:59:59+00', 'https://santapod.co.uk/', 'Santa Pod official calendar', 'https://santapod.co.uk/calendar.php'),
  ('santa-pod-raceway', 'Public Drift Day', 'santa-pod-public-drift-day-2026-11-25', 'Operator-listed drift day on a closed venue. Confirm entry and technical rules before travel.', 'driver_training', 'driver', true, timestamptz '2026-11-25 00:00:00+00', timestamptz '2026-11-25 23:59:59+00', 'https://santapod.co.uk/', 'Santa Pod official calendar', 'https://santapod.co.uk/calendar.php')
) as seed(
  venue_slug, title, slug, description, event_type, participation,
  booking_required, starts_at, ends_at, booking_url, source_label, source_url
)
join public.roadbook_venues v on v.slug = seed.venue_slug
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  event_type = excluded.event_type,
  participation = excluded.participation,
  booking_required = excluded.booking_required,
  starts_at = excluded.starts_at,
  ends_at = excluded.ends_at,
  booking_url = excluded.booking_url,
  source_label = excluded.source_label,
  source_url = excluded.source_url,
  verification_status = excluded.verification_status,
  verified_at = excluded.verified_at,
  published = true,
  all_day = true,
  updated_at = now();

commit;
